### ISSUE TITLE
Overlapping download buttons

### ISSUE THREAD

**Issue by aparcar** [sudhanshu16/openwrt-firmware-selector#17]
![image](https://user-images.githubusercontent.com/16000931/64821175-de487780-d54d-11e9-9a5a-15ac4c75319d.png)

Fix overlapping buttons issue.

**Comment by zhang1pr** [comment]
I couldn't reproduce this. What are the steps and the environment?

**Comment by sudhanshu16** [comment]
Hey @zhang1pr, there is some unrelated issue with the system as of now. 
@aparcar It seems that https://aparcar.stephen304.com doesn't have `.manifest` files in target directories.
