### ISSUE TITLE
Add translation for Spanish

### ISSUE THREAD

**Issue by sudhanshu16** [sudhanshu16/openwrt-firmware-selector#20]
A new JSON file containing the translation to be added to `src/locales/`
Mapping to the `src/i18n.js` must be done accordingly.

Feel free to open more issues for other languages :)

**Comment by kausha15** [comment]
taking up.

**Comment by sudhanshu16** [comment]
@kausha15 Thanks for taking up this issue. It will be great if you can verify the translations with someone who natively speaks Spanish :D

**Comment by kausha15** [comment]
@sudhanshu sure!

**Comment by tosbaha** [comment]
I am taking the Turkish one. Cheers

**Comment by gdelacruzfdez** [comment]
@kausha15 if you need a native Spanish speaker to verify the translations I can do it :smile:

**Comment by kausha15** [comment]
@gdelacruzfdez  sure!
check file at https://github.com/sudhanshu16/openwrt-firmware-selector/pull/24/files
